### ISSUE TITLE
missing libcgraph during initialisation of binder (pygraphviz)

### ISSUE THREAD

**Issue by cokelaer** [jupyterhub/binder#105]
* repository build issues : http://github.com/sequana/sequana

When testing this notebook:

https://mybinder.org/v2/gh/sequana/sequana/master?urlpath=lab/tree/notebooks/coverage.ipynb

I got an error due to missing libcgraph. This is related to the graphviz/pygraphviz package that cannot be installed.

**Comment by betatim** [comment]
It sounds like you need to specify additional dependencies/packages that should be installed.

You can specify additional [apt-get packages to be installed by adding a `apt.txt`](https://mybinder.readthedocs.io/en/latest/using.html#apt-txt)

I usually run things locally with http://repo2docker.readthedocs.io/ to debug these kinds of build problems as turn around is faster compared to using mybinder.org and you get to see more details. repo2docker is the tool BinderHub uses to build things so once it works locally you should be good to go.

---

Can we move this discussion to  http://github.com/sequana/sequana? I don't think this is an issue with mybinder.org/BinderHub in general but specific to sequana.

**Comment by cokelaer** [comment]
thanks. I'm closing this issue, which is now referenced in https://github.com/sequana/sequana/issues/509
