### ISSUE TITLE
Python, Julia and R kernels in the same repo?

### ISSUE THREAD

**Issue by sdwfrost** [jupyterhub/binder#107]
I can't seem to get the Python3, IJulia, and IRkernel to work in the same repository. If I have REQUIRE in the repository, I don't have access to IRkernel (though R, Julia, and Python3 are all installed). I have  `environment.yml` and `runtime.txt`, as per the docs.

See `r-test.ipynb` in [https://github.com/sdwfrost/multi-language-demo] - IRkernel isn't available (https://github.com/sdwfrost/multi-language-demo)

**Comment by betatim** [comment]
https://github.com/binder-examples/multi-language-demo/pull/1#issuecomment-417584848 links to a repository that fixes this. @sdwfrost if you could give a 👍  or 👎 we can close this issue.

**Comment by sdwfrost** [comment]
Thanks! [https://github.com/larssp/mybinder-J-Py-R-oct/](https://github.com/larssp/mybinder-J-Py-R-oct/) is nice and simple.

My repo has expanded to a big polyglot, for which I needed a Dockerfile. It's still a work in progress:

[https://github.com/sdwfrost/polyglot-playground](https://github.com/sdwfrost/polyglot-playground)
