### ISSUE TITLE
Endorsements

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binder#115]
It would be good for promotion and funding purposes to collect endorsement sentences for (my)Binder(Hub|.org). Maybe we can get started with putting them in this thread for the time being.

**Comment by choldgraf** [comment]
I propose that we close this and open up a similar thread in the Discourse channel - WDYT @betatim ?

**Comment by betatim** [comment]
Sounds good to me. We should just remember to move them from where ever we collect them to the Project Binder website. Not totally sure which page that would be though ... :)
