### ISSUE TITLE
docs broken on RTD

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binder#122]
I just noticed that the docs are broken on RTD for latest:

https://readthedocs.org/projects/mybinder/builds/7831997/

@willingc any chance that's the same bug you had noted before in your previous comment about RTD and conda builds? I can take a closer look once my flight lands!

**Comment by willingc** [comment]
Updating the `readthedocs.yml` file such as Min has in https://github.com/jupyterhub/jupyterhub/pull/2179/files should resolve this issue.

@choldgraf I'm going to label this for the PyCon India sprint or new contributor.

**Comment by willingc** [comment]
@Madhu94 This would be a good issue for any folks at the sprint.

**Comment by choldgraf** [comment]
@ashwani-pandey wooo! thanks for this fix 🎉
