### ISSUE TITLE
resolved_ref is not a valid sha1 hexadecimal hash error

### ISSUE THREAD

**Issue by ivotron** [jupyterhub/binder#123]
We're getting this error when using `Git repository` as the source of the "binderized" repo. The repo is https://gitlab.flux.utah.edu/emulab/osdi18-analysis

**Comment by betatim** [comment]
Hi 👋!

In the form on mybinder.org you need to explicitly specify the SHA of the commit you want to use. For GitHub.com and Gitlab.com we can use the respective APIs of the service to find out what the latest commit is but for plain git repositories we can't do that.

For example https://mybinder.org/v2/git/https%3A%2F%2Fgitlab.flux.utah.edu%2Femulab%2Fosdi18-analysis/cc10c099b2cdf46f473a30340433d42b04dac39c is the link generated from filling in the form with the latest commit on master. Screenshot below:

<img width="986" alt="screen shot 2018-09-27 at 08 45 39" src="https://user-images.githubusercontent.com/1448859/46127719-ce972c80-c231-11e8-8ee0-74b0e7156b2c.png">


I think we should make it more obvious from the form that this is a required field. Do you want to make a PR to update the template for the page?

**Comment by ivotron** [comment]
@betatim thanks for the prompt reply! I had tried with `master` and short SHA-1, but I didn't try with the full commit id. Thanks!
