### ISSUE TITLE
pinning distro

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binder#13]
Over a long period of time, there are going to be base upgrades that will break Binders. The easiest to see is upgrading our base image in such a way that breaks `apt.txt`. We are probably going to need to allow users to specify the base distro, as Travis has done with `image: trusty`, etc., and make transitions in our base image extremely infrequent.

Even if we eventually drop support for an old base image, allowing users to specify it will at least have a reproducibility pointer, indicating what they were building on.

**Comment by yuvipanda** [comment]
Should we make this an 'apt.yaml'?

**Comment by minrk** [comment]
It seems to me that a `binder.yaml` is going to make the most sense, rather than proliferating numerous small files.

**Comment by choldgraf** [comment]
@minrk I feel like the repo2docker repo is a better place to discuss this. I'm gonna look over there to see if this conversation is already happening, and if not then I'm gonna open there and close this.

**Comment by choldgraf** [comment]
closing this in favor of: https://github.com/jupyter/repo2docker/issues/166
