### ISSUE TITLE
edit on github url on the docs

### ISSUE THREAD

**Issue by lheagy** [jupyterhub/binder#146]
@choldgraf added instructions for contributors to suggest edits to the docs in #144, and right now the instructions suggest that the user fork and download the repo. This is a lot of overhead for fixing a typo or making small changes. Is there interest in adding an "edit on github" or "improve this page" link in the sidebar? This could replace the "Show source" url or be positioned above it

<img width="640" alt="binder documentation binder 0 1b documentation 2019-01-31 09-42-16" src="https://user-images.githubusercontent.com/6361812/52076332-51fbbe00-2543-11e9-851a-149960bd4078.png">

**Comment by choldgraf** [comment]
I like the idea! I think that Alabaster has a customization setting for something like this https://alabaster.readthedocs.io/en/latest/customization.html
