### ISSUE TITLE
Rebuilding container for tagged commits

### ISSUE THREAD

**Issue by agitter** [jupyterhub/binder#153]
I'd like to use Binder in a repository that has notebooks and many other unrelated files.  I prefer to link to a stable, cached version of the container instead of `master`.  However, I would also like to be able to update that stable version as needed to maintain the notebook code or container environment.  Using different tags seems like a natural way to do this, but I also plan to include the Binder URL in a manuscript that cannot be updated after publication.

If I create a single tag such as `binder-latest`, will Binder rebuild the container if I move that tag from one commit to another?  I expect it will based on my initial testing and what https://mybinder.readthedocs.io/en/latest/tutorials/reproducibility.html says about commit hashes.

**Comment by betatim** [comment]
Yes it will.

**Comment by agitter** [comment]
Thanks for confirming
