### ISSUE TITLE
Build was successful but pages failed to load

### ISSUE THREAD

**Issue by fywu85** [jupyterhub/binder#158]
Hi, I was trying to build my project using the following configuration:
<img width="735" alt="binder_01" src="https://user-images.githubusercontent.com/8881002/54856588-7f015d00-4cb8-11e9-9cfe-2a5425fcbf81.png">
The project was successfully built and the preview is as expected:
<img width="1126" alt="binder_02" src="https://user-images.githubusercontent.com/8881002/54856613-98a2a480-4cb8-11e9-9fca-5230e59fa67e.png">
However, after launching server, I got the following 404 error:
<img width="442" alt="binder_03" src="https://user-images.githubusercontent.com/8881002/54856629-ab1cde00-4cb8-11e9-8ba6-9fbf544bc236.png">
Any pointer to how might I fix the problem? For your reference, you may find the source I used [here](https://github.com/flow-project/flow/tree/binder). Thanks!

**Comment by betatim** [comment]
Take a look at what you get when you launch it without specifying a directory: https://mybinder.org/v2/gh/flow-project/flow/binder

It looks like your repository has a custom `Dockerfile` in it so probably something there doesn't get done as you expect it to work. We recommend against having your own `Dockerfile` as most people don't need one so the added complexity of having to manage one isn't worth it.

I'll close this issue as there doesn't seem to be anything wrong with mybinder.org/BinderHub itself. Let's move the discussion to http://discourse.jupyter.org/c/questions which is where we are directing all support questions and discussions now. It is more discoverable and accessible (bigger community of people able to help out) than GitHub issues.

**Comment by choldgraf** [comment]
(specifically, you probably want to check out this page: https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html)
