### ISSUE TITLE
Timeout when connecting a (public) Elasticsearch database

### ISSUE THREAD

**Issue by jsmanrique** [jupyterhub/binder#163]
I have a notebook that connects with an Elasticsearch database, and while it runs without issues in my laptop, when I execute it through MyBinder ([link](https://gitlab.com/jsmanrique/bitergia-seminars/tree/master/consuming-data-beyond-elasticsearch/notebooks)) I get *timeout* errors:
```
GET http://46.101.128.86:9200/_alias [status:N/A request:10.011s]
Traceback (most recent call last):
  File "/srv/conda/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/srv/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/srv/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

If I test the connection through my browser, it works well, so it seems something is blocking the connection from MyBinder.

I've tried changing the `timeout` and `timeout_request` parameter in the Elasticsearch connection definition `es=Elasticsearch()`, without any change in the result.

Perhaps, it's something I am doing wrong, so, any help would be more than welcome!

**Comment by betatim** [comment]
Outgoing connections from notebooks running on mybinder.org are limited to (essentially) HTTP, HTTPS and git. This is on purpose.

The more ports we open the more attractive we make mybinder.org as a starting point for abuse :-/ so I'd vote to not add this, even though it would solve your problem :-(

**Comment by jsmanrique** [comment]
Thank you @betatim. I understand the limitation and I was trying to ensure that's the reason.

Would a self-hosted BinderHub or a docker image created with repo2docker have the same limitation?

**Comment by betatim** [comment]
A self-hosted BinderHub won't have this as it is a choice the "owner" of the hub has to make. it is controlled at the level of BinderHub so the users who control what repo2docker does (un)forunately can't change this.

**Comment by choldgraf** [comment]
Just to clarify @betatim's point:

* You *can* control this at the level of a BinderHub deployment
* You *can't* control this at the level of a repo2docker image

**Comment by jsmanrique** [comment]
Thank you @choldgraf. I think we can close the issue.
