### ISSUE TITLE
Is it possible to use Binder with a private repo?

### ISSUE THREAD

**Issue by maxmatical** [jupyterhub/binder#183]

**Comment by choldgraf** [comment]
Hi there - you cannot use the public mybinder.org instance with a private repository, though you can deploy your own BinderHub on infrastructure that you configure to allow private repositories.

**Comment by davins90** [comment]
Hi, how is it possible to do this: "though you can deploy your own BinderHub on infrastructure that you configure to allow private repositories."? Thanks
