### ISSUE TITLE
Suggestion for example repo: Shiny app

### ISSUE THREAD

**Issue by pablobernabeu** [jupyterhub/binder#184]
Hi all,

I'd like to suggest a Binder repo for the [examples page](https://mybinder.readthedocs.io/en/latest/examples.html). This [repo is a Shiny app](https://mybinder.org/v2/gh/pablobernabeu/Modality-switch-effects-emerge-early-and-increase-throughout-conceptual-processing/master?urlpath=shiny/Shiny-app/). The Github repo is [this one](https://github.com/pablobernabeu/Modality-switch-effects-emerge-early-and-increase-throughout-conceptual-processing/tree/master/Shiny-app).

Please feel totally free in assessing this, of course.

Thanks,
Pablo

**Comment by choldgraf** [comment]
hey there 👋 I think it's a nice idea! Please feel free to make a PR to the examples page and we'd be happy to merge :-)

**Comment by choldgraf** [comment]
(even better if you add a README.md to the repo with a bit of explanation aobut what is going on)

**Comment by pablobernabeu** [comment]
Awesome -- thank you! 

Will do.
