### ISSUE TITLE
[DOCS] Grafana charts not showing on the status page of mybinder.readthedocs.io

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binder#195]
### Bug description

Hi all,

Just reporting that the grafana charts we show on https://mybinder.readthedocs.io/en/latest/status.html aren't showing up for me

Chrome:
<img width="1392" alt="Screenshot 2020-04-17 at 13 14 04" src="https://user-images.githubusercontent.com/44771837/79568356-9e321000-80ad-11ea-95fd-952c570d9704.png">

Firefox:
<img width="1392" alt="Screenshot 2020-04-17 at 13 13 48" src="https://user-images.githubusercontent.com/44771837/79568390-aa1dd200-80ad-11ea-805c-5659674dc67b.png">

Safari:
<img width="1392" alt="Screenshot 2020-04-17 at 13 13 41" src="https://user-images.githubusercontent.com/44771837/79568441-befa6580-80ad-11ea-9827-b938d861caf5.png">

### Your personal set up

 - OS:
 
 - Version:
 
 - Configuration:

**Comment by manics** [comment]
My Firefox web console (`Tools ➡️  Web Developer ➡️ Web Console`) shows these errors:
```
Load denied by X-Frame-Options: “deny” from “https://grafana.mybinder.org/d-solo/fLoQvRHmk/status?panelId=6&orgId=1&tab=general&theme=light”, site does not permit any framing. Attempted to load into “https://mybinder.readthedocs.io/en/latest/status.html”.

Load denied by X-Frame-Options: “deny” from “https://grafana.mybinder.org/d-solo/fLoQvRHmk/status?panelId=2&orgId=1&tab=general&theme=light”, site does not permit any framing. Attempted to load into “https://mybinder.readthedocs.io/en/latest/status.html”.

Load denied by X-Frame-Options: “deny” from “https://grafana.mybinder.org/d-solo/fLoQvRHmk/status?panelId=4&orgId=1&tab=general&theme=light”, site does not permit any framing. Attempted to load into “https://mybinder.readthedocs.io/en/latest/status.html”.
```
which suggests it has to be fixed on the Grafana side.

I think the last change to the Grafana version was https://github.com/jupyterhub/mybinder.org-deploy/pull/1195 on 12 Oct 2019.

**Comment by manics** [comment]
Do you want to give https://github.com/jupyterhub/mybinder.org-deploy/pull/1410 a go?

**Comment by sgibson91** [comment]
Merged! Let's see if that solves anything 🤞

**Comment by manics** [comment]
Reopening since this is only on staging, not prod yet!
