### ISSUE TITLE
Binder won't reach github repository

### ISSUE THREAD

**Issue by sumanan047** [jupyterhub/binder#196]
**everytime I try to access my github, I see this error:**

Error during build: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byteWaiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerzrnwxg4o'...
HEAD is now at 9e9be65 Setup nbinteract
Error during build: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Any help?

**Comment by choldgraf** [comment]
Can you provide a link to your repo?

**Comment by sumanan047** [comment]
Thanks chris, here is the repo,

https://github.com/sumanan047/nbinteract-tutorial

**Comment by choldgraf** [comment]
hmm - my guess is that there is something wrong with one of your configuration files, it's a bit hard to know which one, but it seems like binder is choking when it tries to read in the configuration in the repository. A quick note, I don't think that generating an environment from `conda` entirely is a good idea - your environment.yml file has a ton of lines that are pinned to very specific versions, but this may not generalize to other platforms. I'd recommend starting with the minimal `requirements.txt` file that will reproduce your analysis

**Comment by sumanan047** [comment]
Thanks again Chris, Did exactly that. Started from scratch again with only pip, no conda. It works now.
