### ISSUE TITLE
The binder R example shiny link is broken

### ISSUE THREAD

**Issue by pnavaro** [jupyterhub/binder#197]
### Bug description
I try to use the [binder R example](https://github.com/binder-examples/r) 

#### Expected behaviour
The shiny app should appears

#### Actual behaviour

ERR_TOO_MANY_REDIRECTS

### How to reproduce

Go to http://mybinder.org/v2/gh/binder-examples/r/master?urlpath=shiny/bus-dashboard/

**Comment by choldgraf** [comment]
ah thanks for spotting this! I think that we got this fixed in https://github.com/jupyter/repo2docker/pull/893 ... once it's deployed on mybinder I'll let you know and then we can give it another shot. The issue was that rStudio split off its Shiny proxy into a separate package

**Comment by choldgraf** [comment]
try it again!

**Comment by pnavaro** [comment]
Magnifique. It works now  with a single environment.yml file too. Merci.

**Comment by choldgraf** [comment]
yahoo! thanks for noticing
