### ISSUE TITLE
Document how to add a "run with Binder" bot using GitHub actions

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binder#202]
I believe in various threads I've seen @hamelsmu show off some pretty nifty GitHub actions to generate Binder badges for PRs and display them in the PR thread. This seems like a nicely-contained feature that we should highlight somewhere! Maybe in these docs? Maybe @hamelsmu would be willing to write up a short-and-sweet description of how to use this that we could add in to the documentation, and link out to the GHA docs for more detailed information?

**Comment by hamelsmu** [comment]
Would be happy to do this

**Comment by hamelsmu** [comment]
@choldgraf I am looking into this now, can you point me at where I can contribute to the docs?  For example, I'm trying to learn about how [this page was made](https://mybinder.readthedocs.io/en/latest/howto/languages.html) but I cannot seem to find that page in this repository.   Any hints here?  

Thank you

**Comment by choldgraf** [comment]
Hey - ah I think you have run into some sub-optimal documentation practices from us 😬 

In an effort to cut down on the duplicated documentation, we've been pulling in pages from the repo2docker documentation into the binder documentation at build time. here's the script that does this:

https://github.com/jupyterhub/binder/blob/master/doc/conf.py#L183

so where you'd *actually* need to update that file is https://github.com/jupyter/repo2docker/blob/master/docs/source/howto/languages.rst

sorry that is confusing :-/

**Comment by hamelsmu** [comment]
Ahhh any tips on how I can preview the docs locally so I can test a PR locally before submission?  

P.S. I will probably have to take a `rst` tutorial before doing this, but I'm ok with that

**Comment by choldgraf** [comment]
hmmm - maybe this is a good time to enable the MyST markdown parser in the repository (https://myst-parser.readthedocs.io)...if you like we can hop on a quick call maybe tomorrow PM and I can step you through the docs build?

and when you build the docs locally those files *should* be downloaded into your local repository (they are just ignored in git), so maybe you could download them once, then comment-out those lines so they don't get re-downloaded, and you can start playing around w/ editing the text?

**Comment by hamelsmu** [comment]
Ok having a call would be really great, I will take you up on that offer.  I'll DM you to setup a time
