### ISSUE TITLE
[DOCS] Out of date docs and bring the Federation list over from BinderHub

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binder#209]
Hi all,

I was looking through our documentation for Federation info and I expected this to be under mybinder.readthedocs.io as it's a mybinder.org specific thing, so I was surprised to find it under binderhub.readthedocs.io.

I also noticed the [who pays for mybinder.org section](https://mybinder.readthedocs.io/en/latest/about.html#who-pays-for-mybinder-org) is out-dated as well as it still mentions the Moore Foundation and singles out Google Cloud. Perhaps this would be a good place to link out to and/or replace with the Federation members/info?

**Comment by choldgraf** [comment]
💯 I think it's a great idea - in general it would be fantastic to do a pass at our docs across multiple projects to make them a bit more streamlined, it has been a while since we've improved them!
