### ISSUE TITLE
Build was successful but pages failed to load 

### ISSUE THREAD

**Issue by gloriamacia** [jupyterhub/binder#224]
### Bug description

The build of my project is successful but the page files to load and returns a 404 : Not Found Error as described [here](https://github.com/jupyterhub/binder/issues/158) though I have no Dockerfile. 
I am following the fastai book tutorial on how to deploy models on binder as shortly described in this blog [post. ](https://www.enricodata.com/post/how-to-deploy-a-deep-learning-model-with-binder-and-voila/)
I added a requirements.txt file as well as a runtime.txt file in my[ github repo](https://github.com/gloriamacia/see-you-later-alligator) and docker image builds correctly, only the server fails to load the page afterward.  As it is the very last step, the logs provide no useful information of what is going on. 

### How to reproduce
Follow[ Step 7 of the blog post tutorial](https://www.enricodata.com/post/how-to-deploy-a-deep-learning-model-with-binder-and-voila/) with [my repo ](https://github.com/gloriamacia/see-you-later-alligator) details. Should be a simple copy paste of the repo URL and the notebook name. Select URL (not file) adding before the notebook name /voila/render/<notebook_name>.

**Comment by betatim** [comment]
It sounds like this is more of a support type of question as your repo launches on mybinder.org for me (without using voila). I think you will have more luck posting on the forum.
