### ISSUE TITLE
chromedriver?

### ISSUE THREAD

**Issue by ognancy4life** [jupyterhub/binder#238]
A colleague of mine is working on a [notebook/repo](https://github.com/Rosenheim-Lab/PCS_COVID) to scrape the COVID-19 case data from our local county's public school board page. Given the urgency of the situation with regard to the health and safety of our community, we'd like to be able to have this run on a public binder so that others can access this ever-changing information. 

Is chromedriver available in Binder? If so, how would we reference its location in the [notebook](https://github.com/Rosenheim-Lab/PCS_COVID/blob/main/dashboard_scrape.ipynb) as `driver_path`? 

Thank you for your help!

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.

**Comment by ognancy4life** [comment]
> In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.

I have joined the jupyter discourse and am trying to create a topic for this and getting the error message "You are not permitted to view the requested resource."
