### ISSUE TITLE
Suport R verison 4+

### ISSUE THREAD

**Issue by SilasK** [jupyterhub/binder#247]
### Proposed change

I like to use up to date R version 4 or 4.1

What I see when using r-conda example is that the irkernel=1.1 installed is not compatible with R version 4
Also when using r example I get a message that v 4 is not supported.

**Comment by manics** [comment]
Please follow this issue, and feel free to open a PR if you've got an idea for how to fix it: https://github.com/jupyterhub/repo2docker/issues/1077
