### ISSUE TITLE
[design] binder loading page

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterhub/binder#32]
A few users of the xtensor binder have reported that they were confused by our "Try it Now" button, which "was redirecting to some binder page". They eventually closed their browser tab.

So it was not obvious to them that something was going to be launched eventually.

Maybe more obvious visual indication that something is loading would help.

(as reported on the gitter chat)

**Comment by choldgraf** [comment]
I think this could be a good next major UI milestone after the binder badge update https://github.com/jupyterhub/binderhub/pull/252

@SylvainCorlay I'm going to open this issue in BinderHub and close this one! Thanks for opening!

https://github.com/jupyterhub/binderhub/issues/271
