### ISSUE TITLE
Open-in-binder browser extension.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/binder#33]
Not asking if we should create one, just saying I did:

https://github.com/Carreau/open-with-binder-firefox-extension

Ok, it's 15 lines and it took me 5 days (3lines/day is not too bad !) but mostly learning how to do it. 

![binderify](https://user-images.githubusercontent.com/335567/33031184-c960650a-ce1d-11e7-83ae-5a57af48369b.gif)

Happy to transfer it to the JupyterHub org, and I think we should try to figure how to publish it on the Addon Store. AFAICT it uses API that _should_ also be compatible with Chrome.

**Comment by choldgraf** [comment]
this is super cool!

**Comment by takluyver** [comment]
Neat :-)

**Comment by betatim** [comment]
Woah! Does it work with the latest firefox? (Asking because ~all my extensions have stopped working so this one would be the only one that does :) )

**Comment by Carreau** [comment]
> Woah! Does it work with the latest firefox?

You mean 57 (stable) ? Not sure I'm only using nightly (59) updated twice a day :-P. It should, I actually think I've tried it on 54 as well, and I've followed the latest docs so all should be good :-)

You could try `about:debugging` and "Load temporary addons", then select the `manifest.json` of the repo (once cloned on your machine). The binder logo should appear on your toolbar.

**Comment by betatim** [comment]
Works!

**Comment by Carreau** [comment]
> Works!

Wow slow down on advertising on twitter :-) I was planning to discuss the name and publishing on mozilla addons :-).

Should we move the extensions to JupyterHub ? (vote with 👍 or 👎 ) on this comment.
And vote for the following comment with the relevant names. (Note, names can have space in them AFAICT).

**Comment by Carreau** [comment]
Name the extension **Binderify**.

**Comment by Carreau** [comment]
Name the extension **Open with Binder**.

**Comment by Carreau** [comment]
Name the extension **Open with MyBinder**.

**Comment by Carreau** [comment]
Happy to give publishing rights to https://addons.mozilla.org, just give me your usernames.

**Comment by choldgraf** [comment]
I'm `choldgraf`, though I know very little about firefox plugins :-)

can I close this BTW? Or would you like to use the issue for discusison?

**Comment by Carreau** [comment]
> I'm choldgraf,

Actually I needed the email so I did your gmail one...

>  though I know very little about firefox plugins :-)

It's ok, it's just if something happen to me that there is another owner :-) 

> can I close this BTW? Or would you like to use the issue for discussion?

Sure.
