### ISSUE TITLE
Update "prepare repo" example

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binder#37]
The section on using conda mentions sklearn/numpy as packages that are hard to install via numpy. They aren't that hard to install really. Change that example to use geopandas or similar.

via https://github.com/jupyterhub/binder/pull/36#discussion_r153929623

**Comment by choldgraf** [comment]
This will be fixed in https://github.com/jupyterhub/binder/pull/47

**Comment by choldgraf** [comment]
closed by #47 !
