### ISSUE TITLE
Incident starting 2017-11-30 4:23PM PST

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binder#39]
Screenshots for https://hackmd.io/CYVgDAZgRhAcBMBaKsLEQFgJzCVkAzAGyKwDGFApvCBAIzADswQA?edit
<img width="1149" alt="screen shot 2017-12-01 at 01 26 52" src="https://user-images.githubusercontent.com/1448859/33462478-08cbda22-d638-11e7-8aa6-1eec42d1dc1d.png">

Times in the screenshot are Zurich (CET) timezone

**Comment by betatim** [comment]
with node=gke-prod-a-default-pool-6ab3d8ec-0h28 set in the grafana dashboard I have and a screenshot of the below expression:

`sum (container_memory_working_set_bytes{image!="",name=~"^k8s_.*",kubernetes_io_hostname=~"^$Node$"}) by (pod_name)`

<img width="1163" alt="screen shot 2017-12-01 at 01 54 02" src="https://user-images.githubusercontent.com/1448859/33462880-96d5f030-d63a-11e7-8677-488100d2ba62.png">

**Comment by choldgraf** [comment]
can we close this one?
