### ISSUE TITLE
wrap OpenRefine, potentially with some kind of `nbrserverproxy` function.

### ISSUE THREAD

**Issue by ctb** [jupyterhub/binder#40]
[OpenRefine](http://openrefine.org/) is an insanely useful Web tool for cleaning up spreadsheets in nice reproducible ways.  I hear that it is one of the most popular [Data carpentry lessons](http://www.datacarpentry.org/OpenRefine-ecology-lesson/) once delivered :).  Since it's a "simple" web app, should be possible to binderize it to make install easier.

**Comment by psychemedia** [comment]
If this can serve to act as a general example for how to set up and run a service that exposes itself on a particular port, it should presumably be possible to use a similar recipe to expose desktop UIs via something like `novnc` to the browser too? 

As as crib for that, https://github.com/dit4c/dockerfile-dit4c-container-qgis shows how to get QGIS running using https://github.com/dit4c/dockerfile-dit4c-container-x11 as a base.

**Comment by betatim** [comment]
https://github.com/jupyterhub/nbserverproxy this is going to be the tool you need to do this. A current example for how to expose RStudio is https://github.com/rocker-org/binder which uses https://github.com/jupyterhub/nbrsessionproxy. The generic parts of which are [being moved](https://github.com/jupyterhub/nbrsessionproxy/pull/22) to `nbserverproxy`.

**Comment by yuvipanda** [comment]
I think @betatim has this covered now?

**Comment by choldgraf** [comment]
yes! closing this since https://github.com/betatim/openrefineder now exists

ping @ctb in case you didn't see this earlier

**Comment by yuvipanda** [comment]
@psychemedia I think wrapping novnc would be *great*...

**Comment by choldgraf** [comment]
oops, I said I would close this and then I didn't...closing now!
