### ISSUE TITLE
How to access a file via FTP from within a Dockerfile?

### ISSUE THREAD

**Issue by davidrpugh** [jupyterhub/binder#43]
My repo needs access to the PATH solver which is available via an [ftp server](ftp://ftp.cs.wisc.edu/math-prog/solvers/path/ampl/).  Here is the [Dockerfile](https://github.com/KAPSARC/pyomo-hackathon/blob/master/Dockerfile) that I am using to build the container.  

Issue I am running into is that the ftp connection keeps timing out. Here is a snippet of the build log.

```
Retrying.

--2017-12-04 06:31:15--  ftp://ftp.cs.wisc.edu/math-prog/solvers/path/ampl/lnx/pathampl
  (try: 4) => ‘pathampl’
Connecting to ftp.cs.wisc.edu (ftp.cs.wisc.edu)|128.105.2.31|:21... failed: Connection timed out.
Retrying.

--2017-12-04 06:33:26--  ftp://ftp.cs.wisc.edu/math-prog/solvers/path/ampl/lnx/pathampl
  (try: 5) => ‘pathampl’
Connecting to ftp.cs.wisc.edu (ftp.cs.wisc.edu)|128.105.2.31|:21... failed: Connection timed out.
Retrying.
```

I have successfully downloaded this file using `wget` and `curl` from outside of a Docker container using

```
wget -q ftp://ftp.cs.wisc.edu/math-prog/solvers/path/ampl/lnx/pathampl
```

or

```
curl ftp://ftp.cs.wisc.edu/math-prog/solvers/path/ampl/lnx/pathampl -o pathampl
```

which makes me think that the issue has to do with Dockerfile.  Any help would be greatly appreciated!

**Comment by yuvipanda** [comment]
Hello! Thank you for opening the issue, and apologies this has affected you!

We explicitly block all ports except for HTTP (80), HTTPS (443) and git (9418). I'm somewhat hesitant to whitelist FTP - it isn't commonly used, and FTP scanners such as [the one from metasploit](https://www.offensive-security.com/metasploit-unleashed/scanner-ftp-auxiliary-modules/) are common. Is it possible for you to download this from a non-FTP source?

**Comment by davidrpugh** [comment]
@yuvipanda Thanks for the quick reply!  I have been looking and so far have not found any other option.

**Comment by takluyver** [comment]
http://ftp.cs.wisc.edu/math-prog/solvers/path/ampl/lnx/pathampl seems to work for me ;-)

**Comment by davidrpugh** [comment]
@takluyver Thanks! Such a simple little fix would never have occurred to me.
