### ISSUE TITLE
Tiny problem with the help prompt

### ISSUE THREAD

**Issue by ColCarroll** [jupyterhub/binder#52]
When opening issues, there are two references to use https://github.com/jupyterhub/binder/new .  It looks like that should probably be "https://github.com/jupyterhub/binder/issues/new" (or just "https://github.com/jupyterhub/binder/issues", to encourage me to search for my problem?)

**Comment by choldgraf** [comment]
Good catch! I think it should be `/binder/issues/new`. Want to make a quick PR for the change? Am happy to review it quickly
