### ISSUE TITLE
eLife Innovation Sprint

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binder#55]
I just came across this:

https://elifesciences.org/events/c40798c3/save-the-date-for-the-elife-innovation-sprint

Seems up the alley of the Binder world, and maybe a good way to connect with some other projects/people/etc. @betatim or @minrk maybe you'd be particularly interested since you're a bit closer already? Or @jzf2101 since you seem to be traveling around the world once per month anyway :-)

**Comment by betatim** [comment]
I registered, not sure yet if I will have time to go.

**Comment by choldgraf** [comment]
I _probably_ won't be able to go, since I have to go to the UK/Europe both in March and June and August, and that is a lot of travel :-(

**Comment by jzf2101** [comment]
I likely won't be able to make it :(

**Comment by minrk** [comment]
I registered

**Comment by choldgraf** [comment]
closing this, since registration is now passed and I assume folks that'll be there already know about it :-)
