### ISSUE TITLE
Idea: Make "Autorun" possible

### ISSUE THREAD

**Issue by MatsGustavsson** [jupyterhub/binder#58]
Hi,
I would like to post an idea (already mentioned in the chat today): 

**Enabling the notebook to "autorun" in a browser** (i.e. not having a user not having to go through "click on cell run or CTRL + SHIFT" etc)?

It would be a great feature because any user (not only Jupyter savvy persons) could dwelve right into the functionality of the notebook! Imagine clicking on a link and getting to a page with only input fields , interactive sliders etc. ready to go straight out of the box!

In any case  I just started using jupyterhub  and the binder and  find them absolutely amazing. Fantastic  achievement from you all and many thanks.

Cheers,
Mats

**Comment by choldgraf** [comment]
Agreed something like this would be useful! I think the best way to do so would be with a notebook or jupyterlab extension, rather than a binder-specific change.

That said, there already is something *kinda* like this, check out the appmode plugin...here's a binder example for it: https://github.com/binder-examples/appmode

**Comment by MatsGustavsson** [comment]
Thanks. I tried it but I get this error which is linked to "tokens" 403 when I click the notebooklink from another pc or smartphone. From my understanding it depends on problem of authenticating the user. 

So it does not really work for my purpose (having a "ready to run" live version on a web-address that you can very easily let someone play with) like "Shiny".

I'll comment also on the appmode plugin.

Thanks again

**Comment by choldgraf** [comment]
hmm - what is the link that you clicked on? can you paste it here?

**Comment by MatsGustavsson** [comment]
Hi Chris,
look here https://hub.mybinder.org/hub/login?next=%2Fhub%2Fuser%2Fmatsgustavsson-finance-jupyter-l7rwx6h6%2Fapps%2FSequentialStructure.ipynb%3Fappmode_scroll%3D0
The file also contains some JS (for hiding code) which does not work-(it worked in nbviewer which is useless if you have ipywidgets).
The file I'm trying to get to run as shiny is https://github.com/MatsGustavsson/finance-jupyter/blob/master/SequentialStructure.ipynb

 

    Il Martedì 9 Gennaio 2018 2:38, Chris Holdgraf <notifications@github.com> ha scritto:
 

 hmm - what is the link that you clicked on? can you paste it here?—

**Comment by choldgraf** [comment]
hey - let's take the conversation over here: https://github.com/jupyterhub/binder/issues/58

I'll close this issue so we aren't duplicating info!
