### ISSUE TITLE
Spec is not of the form "user/repo/ref", provided: "/master".

### ISSUE THREAD

**Issue by ggrrll** [jupyterhub/binder#63]
Hi, 

I am totally new to this tool.

I have got the `Spec is not of the form "user/repo/ref", provided: "/master".` message with some repos and also with https://github.com/binder-examples/jupyter-rise/blob/master/index.ipynb 

Thanks for clarification.

**Comment by choldgraf** [comment]
hey - how are you using the tool? did you go to `mybinder.org` and follow the instructions on that page? more information about the steps you took would be useful

**Comment by ggrrll** [comment]
Hi,

sorry, yeah,  I put the url on `mybinder.org`

I managed to make it work with https://github.com/binder-examples/jupyter-rise/ - I guess the problem was that I was passing the whole notebook
