### ISSUE TITLE
Office hour #1

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binder#67]
We will have an office hour on Thursday February 22nd at 6pm Zurich/9am Berkely time.

The idea is to offer a time and place for people who are using mybinder.org and all its related tools and who have questions about them to meet. There will be several members of the binder team there too. The main meeting point will be the gitter channel (https://gitter.im/jupyterhub/binder) and maybe also a video chat. If you have questions about your Binderhub deployment, want to get involved with the projects or chat about ways to use it come and stop by.

This is an experiment for us as well, so what exactly will happen is up in the air. 

---

How about the above as a starting point to publicise the office hours?

**Comment by yuvipanda** [comment]
Both you and @willingc will be away next Thursday, so we should pick a better time!

**Comment by betatim** [comment]
Changed date to 22nd Feb. Feel free to edit the top comment with ideas about a time slot.

**Comment by betatim** [comment]
Office hours held and we even had some people asking questions!

**Comment by willingc** [comment]
@betatim That's awesome!
