### ISSUE TITLE
suggest removing 'Important' note about using name field for environment.yml

### ISSUE THREAD

**Issue by fomightez** [jupyterhub/binder#79]
I was reviewing if anything special is needed for an "environment.yml", and I note that it currently says said, "Important, You must leave the environment.yml’s name field empty for this to work out of the box." Is that outdated and should be removed?  
I question it because I have had ones with a name in name: field work. I copied one that works from https://github.com/quantopian/qgrid-notebooks that works and it has "name: qgrid-environment" for `name:`.

**Comment by minrk** [comment]
Yeah, it's not true that the name field must be omitted. It will be ignored the way it works now.

**Comment by betatim** [comment]
@fomightez can you help me find where in the docs it is? I just tried to grep for it but can't find it :-/

**Comment by fomightez** [comment]
Sorry, about that. I see it at http://repo2docker.readthedocs.io/en/latest/usage.html#environment-yml . 

Which now makes me wonder why I put it here and not repo2docker? Sorry again. I probably was unclear about the underlying different pieces.
