### ISSUE TITLE
https://github.com/IQSS/workshops isn't building properly

### ISSUE THREAD

**Issue by pdurbin** [jupyterhub/binder#80]
Hi! 4144d03 at https://github.com/jupyterhub/binderhub/commit/4144d0340473d81b59bf3eb1c950cc7c4aa115ab#diff-1a1c3dd142f76a5fad803a0c52839881 seems to be telling me that I'm in the right issue tracker tor report a repository isn't building properly.

I let this repo run for over an hour, but it seems stuck on the "Pushing" stage (the "Waiting" and "Building" Stages seemed fairly slow as well, taking several minutes) https://github.com/IQSS/workshops

Here's a screenshot after a hour and twenty minutes but it looked like this after ten minutes as well:

![screen shot 2018-03-12 at 11 59 47 am](https://user-images.githubusercontent.com/21006/37295129-bae92098-25ed-11e8-96ea-e1ff9afccae6.png)

To give you a little more context, I hadn't heard of BinderHub under @aculich mentioned it at http://irclog.iq.harvard.edu/dataverse/2018-03-02#i_64028 and he and I chatted more about a potential integration of Dataverse and BinderHub on Friday. I took some notes at https://docs.google.com/document/d/12njDDHHfoNdos0By3lKlxYbRWLsAp8Eo-AGpjuBF_rY/edit?usp=sharing

This morning I asked @izahn if he had heard of BinderHub and he hadn't but he's well aware of tmpnb because he uses it in a somewhat similar service that he runs using code he wrote at https://github.com/IQSS/iqss-jupyter-notebook . Ista is also the author of the "workshops" repo above that's failing. He and I did note the notice at the top of https://github.com/jupyter/tmpnb that says, "DEPRECATED - See BinderHub project".

**Comment by betatim** [comment]
Just tried it and https://mybinder.org/v2/gh/IQSS/workshops/master launched (eventually) for me.

I also had a quick look at the contents of the repo and there doesn't seem to be any binder specific build instructions in there. Is that on purpose?

The repository itself uses up about 1GB once it is in a docker container. As a result the image is quite large which means it can take quite a while for it to be pushed to our registry and then when you launch it it has to be pulled from the registry to the node on which it is being executed (which might be different for different users). At the moment I think all you can do is be patient :-/

**Comment by pdurbin** [comment]
@betatim thanks for taking a look. Really, this was just me and @izahn staring at the Binder interface for the first time and giving it a try. If Binder-specific instructions are required in the git repo, this should probably be mentioned near the input box for "GitHub repo or URL".

Later, @izahn said that https://github.com/nmbrodnax/iqss-python-intro seemed to work fine. So you're probably right that it has something to do with the size of the workshops repo. I'm glad to hear it worked, eventually. I'll go ahead and close this issue. Thanks!
