### ISSUE TITLE
Binder subfolder not searched?

### ISSUE THREAD

**Issue by alexgoodell** [jupyterhub/binder#82]
See this commit https://github.com/alexgoodell/uganda-model/tree/b5fb35bad63d9edff6c6a976dede83150506deaa

and this binder attempt https://mybinder.org/v2/gh/alexgoodell/uganda-model/b5fb35bad63d9edff6c6a976dede83150506deaa

**Comment by choldgraf** [comment]
that is...pretty weird. I just tried as well and it does in fact seem to
miss it. I just tried building another repository w/ a "binder" folder and
this one worked. I wonder if you can try creating a branch and using that?
If that works, but using a specific commit doesn't, then that's probably a
bug.

**Comment by betatim** [comment]
This looks related https://github.com/jupyter/repo2docker/issues/141

**Comment by cudmore** [comment]
I have a binder/ folder in the root of my repo but my Dockerfile trumps binder/ and gets parsed during build. I want mybinder to look in binder/ folder for config options and ignore the Dockerfile in my root? It seems this is 'expected' behavior:

> Dockerfile: If a Dockerfile is present in a repository, it will take precedence over all other configuration files (which will be ignored).

Does 'precedence over all other configuration files' include ignoring 'binder/' folder? Can we get configurations specified in binder/ to trump Dockerfile in root?

**Comment by choldgraf** [comment]
hmmm, if `binder/` does get skipped, it shouldn't be :-)

**Comment by choldgraf** [comment]
opened up #84 to figure this out

**Comment by choldgraf** [comment]
I believe this will be closed by https://github.com/jupyter/repo2docker/pull/277

@cudmore can you give a link to your repo?
