### ISSUE TITLE
Confusion when trying to figure out what repo a binder link points to

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binder#89]
Recently @tjd2002 posted some comments about their "first time user" experience clicking a Binder link in the eLife article. I'll post their thoughts in their entirety below:

* Hi all, I encountered my first Binder link in the wild this week, and wanted to capture and share that 'new user experience'. Before I go submitting issues, I thought I'd share thoughts here
* I clicked the big blue 'Launch Binder' button from the elife blog post here (https://elifesciences.org/labs/8653a61d/introducing-binder-2-0-share-your-interactive-research-environment)
* Turns out the upstream data source used in that example had changed format, so the import was broken. Being a good citizen (and wanting a learning experience) I figured I'd try to fix it and submit a pull request
* Since I did not manually create the binder (but instead just clicked a button), I struggled at first to figure out where to find the source.
* I did see the interstitial mybinder.org page, but then I was automatically forwarded to a bare notebook page: https://hub.mybinder.org/user/wildtreetech-explore-open-data-7u6uw3bw/notebooks/bikes-per-week.ipynb
* Where I'm going with all this is... I think that the unbranded Notebook page leaves a naive user (like myself) a little bit adrift
* I ended up finding the source repo by using the file browser to find a README.md 
* But then it took me a while longer to figure out that the Big Blue Button (tm) was pointing to a particular tag
Ideally, there would have been a prominent link back to the Repo (and Ref) that was used to build the binder

## Some challenges to overcome

This is me spit-balling a few of the challenges here:

1. The eLife post had a binder link that pointed to a data source that changed, thus rendering the binder in an error state when run by users
    * We should be careful to make our binders air-tight when we make big public posts that'll get a lot of traffic.
    * We should fix up @betatim 's tag so that it points to an updated repo that will now work, since that eLife post will continue to see traffic
2. It was difficult to determine which repository the binder pointed to once you were in the live session.
    * We should give a visual cue so users can figure out which repository they're running. We could do this with a UI change we inject into the page (e.g. I think @minrk 's appendix PR in repo2docker could help with this).

cc @willingc

**Comment by tjd2002** [comment]
I think solving (2) will also help with (1)! If it is easier for users to identify the source repo(+tag/commit/branch), they should be more likely to file timely issues when things break. 

To give a bit more color: I first went looking for something like the "Edit on Github" button in readthedocs, or the ubiquitous "Fork me on Github" corner ribbons. I also looked through menu options for something marked 'Binder' that would help me understand the history/state/origins of this notebook. I next inspected the URL, which gave me not-quite-enough information to reconstruct the correct repo location. I guess all of those would be candidates for how to get this information to a user. Not sure, technically, the best place to inject this kind of information.

More generally, I guess I was surprised that there was no Binder-specific chrome on the notebook page, given that I had just clicked on a 'Launch Binder' button. Now that I understand the project a little better, this makes more sense to me (all that should happen is an interactive data environment should magically appear and be usable), but this was my experience on first encounter.

**Comment by betatim** [comment]
The repo and link from eLife should work again thanks to @tjd2002. I am a bit surprised/annoyed that the data file can change and remain reachable at the same URL. Something to pass on to the Open Data Zurich people.

**Comment by choldgraf** [comment]
I think we can close this since there are already

https://github.com/jupyterhub/binderhub/issues/160
https://github.com/jupyterhub/binderhub/issues/260
https://github.com/jupyterhub/binderhub/issues/196

open. @tjd2002 I'll close this, but feel free to re-open if you wish!
