### ISSUE TITLE
First-class IHaskell support

### ISSUE THREAD

**Issue by vaibhavsagar** [jupyterhub/binder#90]
Hi! I was hoping we could work out how to support [IHaskell](https://github.com/gibiansky/IHaskell/) as a first-class citizen on mybinder.org. The `Dockerfile` in that repo works, as well as [this one](https://github.com/vaibhavsagar/ihaskell-mybinder/blob/cf87c1be6beabebf8570b85ae4b8611aa8779ead/Dockerfile), and I think that's a good start. What would the next step be?

**Comment by betatim** [comment]
I am not sure I understand what "first class" would mean in this context.

Are you thinking of adding a file to specify haskell package manager packages that get installed by default like http://repo2docker.readthedocs.io/en/latest/samples.html#r-environment-install-r is for R? So this would be adding a new build pack to repo2docker.

**Comment by vaibhavsagar** [comment]
Yes, that's it exactly. Thanks, I will look into build packs.

**Comment by choldgraf** [comment]
@vaibhavsagar mind if we move this over to repo2docker, now that we know the addition would need to happen there?

**Comment by vaibhavsagar** [comment]
Sure!
